# -*- coding: utf-8 -*-
"""VJTI MTECH RAILWAY PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12V3omBmIqSLI3GqIaVvyNCyUpqC-3gjw
"""

# ==============================================================================
# Advanced Predictive Modeling for Railway Infrastructure
# Implementation: Data Processing, OLS, XGBoost, SHAP, and PERT/CPM Analytics
# ==============================================================================

# 1. Install required dependencies (run this if Colab lacks any of these)
!pip install xgboost shap pandas numpy statsmodels matplotlib scipy openpyxl

import pandas as pd
import numpy as np
import xgboost as xgb
import statsmodels.api as sm
import shap
import matplotlib.pyplot as plt
from scipy.stats import norm
import warnings
warnings.filterwarnings('ignore')

# ------------------------------------------------------------------------------
# 2. Data Ingestion and Feature Engineering
# ------------------------------------------------------------------------------
# Load the dataset from the uploaded Excel file
file_path = 'VJTI MTECH PROJECT TRAINING RAILWAY DATA.xlsx'
df = pd.read_excel(file_path)

# Ensure Date columns are parsed correctly
df['Original_Commissioning'] = pd.to_datetime(df['Original_Commissioning'])
df['Revised_Commissioning'] = pd.to_datetime(df['Revised_Commissioning'])

# Derive Target Variables
# Schedule Delay in Years (calculating absolute days difference / 365.25)
df['Delay_Years'] = (df['Revised_Commissioning'] - df['Original_Commissioning']).dt.days / 365.25

# Cost Overrun Percentage
df['Cost_Overrun_Pct'] = ((df['Revised_Cost_Cr'] - df['Original_Cost_Cr']) / df['Original_Cost_Cr']) * 100

# Define Independent Features (X) and Dependent Targets (y)
features = ['Length_Km', 'Original_Cost_Cr', 'Land_Acq_Pct',
            'Agg_Rainfall_mm', 'Labor_Avail_Idx', 'Mineral_Mat_Idx']

X = df[features].astype(float)
y_delay = df['Delay_Years'].astype(float)
y_cost = df['Cost_Overrun_Pct'].astype(float)

# ------------------------------------------------------------------------------
# 3. Ordinary Least Squares (OLS) Baseline Modeling
# ------------------------------------------------------------------------------
print("--- OLS Regression Results (Target: Cost Overrun %) ---")
X_ols = sm.add_constant(X) # Add y-intercept
ols_model = sm.OLS(y_cost, X_ols).fit()
print(ols_model.summary())
print("\n" + "="*80 + "\n")

# ------------------------------------------------------------------------------
# 4. XGBoost Predictive Modeling
# ------------------------------------------------------------------------------
# Initialize the Extreme Gradient Boosting Regressor
xgb_regressor = xgb.XGBRegressor(
    objective='reg:squarederror',
    n_estimators=150,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)
# Train the model on the Delay Target
xgb_regressor.fit(X, y_delay)
print("--- XGBoost Training ---")
print("XGBoost algorithm successfully trained for Schedule Delay prediction.")
print("\n" + "="*80 + "\n")

# ------------------------------------------------------------------------------
# 5. SHAP (Explainable AI) Interpretability Analysis
# ------------------------------------------------------------------------------
# Instantiate the TreeExplainer for the XGBoost model
explainer = shap.TreeExplainer(xgb_regressor)
shap_values = explainer(X)

# Generate Global Feature Importance (Summary Plot)
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, X, show=False)
plt.title("SHAP Global Summary: Drivers of Schedule Delay")
plt.tight_layout()
plt.show()

# Generate Local Interpretability (Waterfall Plot) for a specific project
# e.g., PRJ_012 (Ahilyanagar-Parli Vaijnath New Line) which is at index 11
target_index = 11
plt.figure()
# SHAP waterfall plot expects an Explanation object for a single prediction
shap.plots.waterfall(shap.Explanation(values=shap_values[target_index],
                                      base_values=explainer.expected_value,
                                      data=X.iloc[target_index],
                                      feature_names=features), show=False)
plt.title(f"SHAP Waterfall Plot for {df['Project_ID'].iloc[target_index]}")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------------------
# 6. PERT and CPM Network Analysis Logic
# ------------------------------------------------------------------------------
def execute_pert_cpm(tasks_dict):
    """
    Ingests an Activity-on-Node dictionary and computes PERT expected durations,
    variances, and executes the CPM forward/backward passes to identify the critical path.
    """
    network = {}

    # PERT Calculations
    for node, data in tasks_dict.items():
        O, M, P = data['O'], data['M'], data['P']
        TE = (O + 4*M + P) / 6.0
        variance = ((P - O) / 6.0) ** 2
        network[node] = {
            'TE': TE, 'Var': variance, 'preds': data['preds'],
            'ES': 0.0, 'EF': 0.0, 'LS': float('inf'), 'LF': float('inf'), 'Slack': 0.0
        }

    # CPM Forward Pass
    for node in network:
        if not network[node]['preds']:
            network[node]['ES'] = 0.0
        else:
            network[node]['ES'] = max([network[p]['EF'] for p in network[node]['preds']])
        network[node]['EF'] = network[node]['ES'] + network[node]['TE']

    project_completion_time = max([data['EF'] for data in network.values()])

    # CPM Backward Pass
    for node in reversed(list(network.keys())):
        successors = [t for t, d in network.items() if node in d['preds']]
        if not successors:
            network[node]['LF'] = project_completion_time
        else:
            network[node]['LF'] = min([network[s]['LS'] for s in successors])
        network[node]['LS'] = network[node]['LF'] - network[node]['TE']
        network[node]['Slack'] = network[node]['LS'] - network[node]['ES']

    # Identify Critical Path and compute Project Standard Deviation
    critical_path = [node for node, d in network.items() if abs(d['Slack']) < 1e-5]
    project_variance = sum([network[node]['Var'] for node in critical_path])
    project_std = np.sqrt(project_variance)

    return project_completion_time, project_std, critical_path, network

# Simulated Task Network for a Railway Civil Works Phase
project_tasks = {
    'T1': {'O': 10, 'M': 15, 'P': 30, 'preds': []},       # Administrative Approvals
    'T2': {'O': 20, 'M': 40, 'P': 90, 'preds': ['T1']},   # Land Acquisition
    'T3': {'O': 15, 'M': 25, 'P': 60, 'preds': ['T2']},   # Earthworks (High Rain Variance)
    'T4': {'O': 30, 'M': 40, 'P': 55, 'preds': ['T3']},   # Track Linking
    'T5': {'O': 10, 'M': 12, 'P': 20, 'preds': ['T4']}    # Electrification & Signalling
}

expected_duration, std_dev, cp, network_details = execute_pert_cpm(project_tasks)

print("--- PERT/CPM Schedule Network Analysis ---")
print(f"Expected Project Duration: {expected_duration:.2f} Weeks")
print(f"Critical Path Sequence: {' -> '.join(cp)}")
print(f"Project Standard Deviation: {std_dev:.2f} Weeks")

# Probability Analysis using Z-Score
# What is the probability of completing the project within 150 weeks?
target_deadline = 150
z_score = (target_deadline - expected_duration) / std_dev
probability_pct = norm.cdf(z_score) * 100
print(f"Probability of completion by Week {target_deadline}: {probability_pct:.2f}%")

import pandas as pd
import numpy as np

# Set seed for reproducible ML feature generation
np.random.seed(42)

# Load Data
df = pd.read_csv('Projects_Report_Railways.csv')
df.columns = df.columns.str.replace('\n', ' ').str.replace('(', '').str.replace(')', '').str.strip()

# 1. State Mapping based on Implementing Agency Regional Zones
def assign_state(agency):
    agency = str(agency).lower()
    if 'east coast' in agency or 'ecor' in agency: return 'Odisha'
    elif 'east central' in agency or 'ecr' in agency or 'patna' in agency: return 'Bihar'
    elif 'south central' in agency or 'scr' in agency: return 'Telangana'
    elif 'north western' in agency or 'nwr' in agency: return 'Rajasthan'
    elif 'south western' in agency or 'swr' in agency or 'k-ride' in agency or 'karnataka' in agency: return 'Karnataka'
    elif 'western railway' in agency or 'wr' in agency: return 'Gujarat'
    elif 'north central' in agency or 'ncr' in agency or 'ner' in agency or 'north eastern' in agency: return 'Uttar Pradesh'
    elif 'central railway' in agency or 'cr' in agency or 'mrvc' in agency or 'mumbai' in agency or 'mridc' in agency: return 'Maharashtra'
    elif 'northeast frontier' in agency or 'nfr' in agency or 'northeast' in agency: return 'Assam'
    elif 'secr' in agency or 'south east central' in agency: return 'Chhattisgarh'
    elif 'eastern railway' in agency or 'er' in agency or 'south eastern' in agency or 'ser' in agency or 'kolkata' in agency: return 'West Bengal'
    elif 'northern' in agency or 'nr' in agency: return 'Punjab'
    else: return 'Madhya Pradesh'

df['State'] = df['Implementing Agency'].apply(assign_state)

# 2. Generate ML specific Synthetic Data Distributions per State
def generate_rainfall(state):
    high_rain = ['Assam', 'Maharashtra', 'West Bengal', 'Odisha']
    med_rain = ['Bihar', 'Uttar Pradesh', 'Chhattisgarh', 'Telangana']
    if state in high_rain:
        return np.random.normal(2000, 300)
    elif state in med_rain:
        return np.random.normal(1100, 200)
    else:
        return np.random.normal(600, 150)

df['Agg_Rainfall_mm'] = df['State'].apply(generate_rainfall).clip(lower=200).round(1)

# Generate Land Acq Pct (correlated structurally with physical progress)
df['Land_Acq_Pct'] = (df['Physical Progress in %'] + np.random.normal(15, 10, len(df))).clip(0, 100).round(1)

# Generate Labor and Mineral Indices
df['Labor_Avail_Idx'] = np.random.normal(0.80, 0.08, len(df)).clip(0.5, 1.0).round(2)
df['Mineral_Mat_Idx'] = np.random.normal(1.20, 0.12, len(df)).clip(1.0, 1.6).round(2)

# Fix missing revised cost by copying original cost for clean baseline data
df['Revised Cost in cr.'] = df.apply(lambda row: row['Original Cost in cr.'] if row['Revised Cost in cr.'] == 0 else row['Revised Cost in cr.'], axis=1)

# Drop any projects with 0 Original Cost to prevent Division by Zero in Cost Overrun algorithms
df = df[df['Original Cost in cr.'] > 0]

# 3. Finalize and Export
final_cols = [
    'Project Code', 'Project Name', 'State', 'Original Cost in cr.', 'Revised Cost in cr.',
    'Physical Progress in %', 'Original Date of Commissioning', 'Revised Date of Commissioning',
    'Land_Acq_Pct', 'Agg_Rainfall_mm', 'Labor_Avail_Idx', 'Mineral_Mat_Idx'
]

output_df = df[final_cols].copy()
output_df.to_csv('Nationwide_Railways_ML_Training_Data.csv', index=False)
print(output_df['State'].value_counts())
print("\nExported Nationwide_Railways_ML_Training_Data.csv successfully.")

# 1. Install necessary dependencies for Colab environment
!pip install xgboost shap pandas numpy statsmodels matplotlib scikit-learn openpyxl

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import xgboost as xgb
import statsmodels.api as sm
import shap
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# 2. Data Ingestion & Structural Alignment
mh_df = pd.read_excel('VJTI MTECH PROJECT TRAINING RAILWAY DATA.xlsx')
nw_df = pd.read_excel('Nationwide_Railways_ML_Training_Data.xlsx')

# Standardize Nationwide column names to match the established Maharashtra schema
nw_df = nw_df.rename(columns={
    'Project Code': 'Project_ID',
    'Project Name': 'Project_Name_and_Location',
    'Original Cost in cr.': 'Original_Cost_Cr',
    'Revised Cost in cr.': 'Revised_Cost_Cr',
    'Physical Progress in %': 'Physical_Progress_Pct',
    'Original Date of Commissioning': 'Original_Commissioning',
    'Revised Date of Commissioning': 'Revised_Commissioning'
})

# Explicitly tag the state for the localized dataset before merging
mh_df['State'] = 'Maharashtra'

# Define common operational features for the unified matrix
common_cols = [
    'Project_ID', 'Project_Name_and_Location', 'State',
    'Original_Cost_Cr', 'Revised_Cost_Cr',
    'Original_Commissioning', 'Revised_Commissioning',
    'Land_Acq_Pct', 'Agg_Rainfall_mm', 'Labor_Avail_Idx', 'Mineral_Mat_Idx'
]

# Concatenate results for both training datasets into a single framework
combined_df = pd.concat([mh_df[common_cols], nw_df[common_cols]], ignore_index=True)

# 3. Target Variable Engineering
combined_df['Original_Commissioning'] = pd.to_datetime(combined_df['Original_Commissioning'], errors='coerce')
combined_df['Revised_Commissioning'] = pd.to_datetime(combined_df['Revised_Commissioning'], errors='coerce')

# Target 1: Schedule Delay (Years)
combined_df['Delay_Years'] = (combined_df['Revised_Commissioning'] - combined_df['Original_Commissioning']).dt.days / 365.25
# Target 2: Cost Overrun (%)
combined_df['Cost_Overrun_Pct'] = ((combined_df['Revised_Cost_Cr'] - combined_df['Original_Cost_Cr']) / combined_df['Original_Cost_Cr']) * 100

# Drop projects lacking clear commissioning dates to maintain clean learning data
combined_df = combined_df.dropna(subset=['Delay_Years', 'Cost_Overrun_Pct'])
print(f"Total Unified Training Samples: {combined_df.shape[0]} Projects\n")

# 4. Feature Selection & Train-Test Split (Teaching the Algorithm)
features = ['Original_Cost_Cr', 'Land_Acq_Pct', 'Agg_Rainfall_mm', 'Labor_Avail_Idx', 'Mineral_Mat_Idx']
X = combined_df[features].astype(float)
y_delay = combined_df['Delay_Years'].astype(float)

# Split data: 80% to "teach" the model concepts, 20% to "test" its learning
X_train, X_test, y_train, y_test = train_test_split(X, y_delay, test_size=0.2, random_state=42)

# 5. Baseline: Ordinary Least Squares (OLS) Linear Regression
# Evaluates baseline trend analysis against complex ML methodologies
print("="*60)
print("1. STATISTICAL BASELINE: OLS REGRESSION")
print("="*60)
X_train_ols = sm.add_constant(X_train)
ols_model = sm.OLS(y_train, X_train_ols).fit()
print(ols_model.summary())
print("\n")

# 6. Advanced Machine Learning: XGBoost
print("="*60)
print("2. MACHINE LEARNING: XGBOOST REGRESSOR")
print("="*60)
xgb_model = xgb.XGBRegressor(
    objective='reg:squarederror',
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

# Teach the model the non-linear concepts on the combined training data
xgb_model.fit(X_train, y_train)

# Evaluate how well the algorithm generalized concepts to unseen test data
train_predictions = xgb_model.predict(X_train)
test_predictions = xgb_model.predict(X_test)

print(f"Training Data R-squared Accuracy: {r2_score(y_train, train_predictions):.2f}")
print(f"Testing Data R-squared Accuracy:  {r2_score(y_test, test_predictions):.2f}")
print(f"Mean Absolute Error (Test Data):  {mean_absolute_error(y_test, test_predictions):.2f} Years\n")

# 7. Explainable AI: SHAP Interpretability
print("="*60)
print("3. MODEL INTERPRETABILITY (SHAP)")
print("="*60)
# Explain exactly how the model weights national vs. regional concepts
explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer(X_train)

# Global Summary Plot: Visualizing the overarching learned drivers of delay
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, X_train, show=False)
plt.title("SHAP Global Summary: Unified Nationwide & Regional Drivers of Delay")
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np

# Seed for reproducibility
np.random.seed(42)

# List of real project descriptions matching Indian railway network naming conventions
project_names = [
    "Virar-Dahanu Road 3rd & 4th Line", "Ahmedabad-Botad Gauge Conversion",
    "Khurda Road-Bolangir New Line", "Jhansi-Manikpur Doubling",
    "Mau-Ghazipur-Tarighat New Line", "Bengaluru-Hassan Line Doubling",
    "Howrah-Bardhaman Chord Line", "New Bongaigaon-Rangia-Kamakhya Doubling",
    "Ajmer-Chittaurgarh Gauge Conversion", "Kazipet-Balharshah 3rd Line",
    "Indore-Manmad New Line", "Wardha-Nanded New Line",
    "Pune-Miraj-Londa Doubling", "Daund-Manmad Doubling",
    "Itarsi-Nagpur 4th Line", "Panvel-Karjat Suburban Corridor",
    "Kalyan-Kasara 3rd Line", "Gonda-Gorakhpur Doubling",
    "Sabarmati-Agra High-Speed Link", "Raipur-Titlagarh Doubling",
    "Katni-Bina 3rd Line", "Bhusawal-Khandwa 3rd & 4th Line",
    "Solapur-Tuljapur-Osmanabad New Line", "Gooty-Renigunta Doubling",
    "Secunderabad-Mahabubnagar Doubling", "Harbour Line Goregaon-Borivali Extension",
    "Ratlam-Neemuch Doubling", "Ranchi-Lohardaga Gauge Conversion",
    "Hospet-Hubli-Tinaighat Doubling", "Sevok-Rangpo New Line"
]

states = ['Maharashtra', 'Gujarat', 'Odisha', 'Karnataka', 'Uttar Pradesh', 'Bihar', 'West Bengal', 'Assam', 'Rajasthan', 'Telangana']
n_projects = len(project_names)

data = {
    'Project_ID': [f'TEST_{i:03d}' for i in range(1, n_projects + 1)],
    'Project_Name_and_Location': project_names,
    'State': np.random.choice(states, n_projects),
    'Length_Km': np.random.uniform(25, 360, n_projects).round(1),
    'Original_Cost_Cr': np.random.uniform(200, 5000, n_projects).round(1),
    'Land_Acq_Pct': np.random.uniform(30, 100, n_projects).round(1),
    'Agg_Rainfall_mm': np.random.uniform(500, 2400, n_projects).round(1),
    'Labor_Avail_Idx': np.random.uniform(0.70, 0.90, n_projects).round(2),
    'Mineral_Mat_Idx': np.random.uniform(1.10, 1.40, n_projects).round(2),
    'Actual_Delay_Years': np.random.uniform(1.0, 4.5, n_projects).round(2)
}

test_df = pd.DataFrame(data)

# PERT Task Durations (O, M, P) in weeks
test_df['T1_O'], test_df['T1_M'], test_df['T1_P'] = 8, 12, 22
test_df['T2_O'], test_df['T2_M'] = 20, 35
test_df['T2_P'] = test_df['T2_M'] + ((100 - test_df['Land_Acq_Pct']) * 1.4).astype(int)
test_df['T3_O'], test_df['T3_M'] = 15, 25
test_df['T3_P'] = test_df['T3_M'] + (test_df['Agg_Rainfall_mm'] / 45).astype(int)
test_df['T4_O'] = (test_df['Length_Km'] / 12).astype(int) + 6
test_df['T4_M'] = test_df['T4_O'] + 14
test_df['T4_P'] = test_df['T4_M'] + 22
test_df['T5_O'], test_df['T5_M'], test_df['T5_P'] = 10, 16, 26

test_df['Target_Deadline_Weeks'] = test_df['T1_M'] + test_df['T2_M'] + test_df['T3_M'] + test_df['T4_M'] + test_df['T5_M'] + 12

# Export to Excel
file_name = 'Railway_Testing_Data_PERT_ML.xlsx'
test_df.to_excel(file_name, index=False)
print(f"File [{file_name}] successfully created with {n_projects} named projects.")

# ==============================================================================
# ADVANCED INFRASTRUCTURE PREDICTIVE ANALYTICS PIPELINE
# ==============================================================================
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_absolute_percentage_error
import shap
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Configure environment for clean output
warnings.filterwarnings('ignore')
np.random.seed(42)

# ==============================================================================
# 1. DATASET GENERATION: 30 REALISTIC RAILWAY INFRASTRUCTURE SAMPLES
# ==============================================================================
# Synthesizing data reflecting actual MoSPI and Indian Railway metrics
data_matrix = {
    'Project_ID': [f'PRJ_{i:03d}' for i in range(1, 31)],
    'Project_Name': [
        "Pune-Miraj-Londa Doubling", "Hotgi-Kudgi-Gadag Doubling", "Manmad-Jalgaon 3rd Line",
        "Jabalpur-Gondia Gauge Conv.", "Chhindwara-Nagpur Gauge Conv.", "Panvel-Pen Doubling",
        "Pen-Roha Doubling", "Udhna-Jalgaon Doubling", "Mudkhed-Parbhani Doubling",
        "Bhusawal-Jalgaon 3rd Line", "Daund-Gulbarga Doubling", "Ahilyanagar-Parli Vaijnath NL",
        "Baramati-Lonand New Line", "Wardha-Nanded New Line", "Indore-Manmad New Line",
        "Wadsa-Gadchiroli New Line", "Jalna-Jalgaon New Line", "Itarsi-Nagpur 4th Line",
        "Virar-Dahanu 3rd & 4th Line", "Panvel-Karjat Suburban", "Jalgaon-Bhusawal 4th Line",
        "Daund-Manmad Doubling", "Wardha-Nagpur 3rd Line", "Wardha-Ballarshah 3rd Line",
        "Itarsi-Nagpur 3rd Line", "Rajnandgaon-Nagpur 3rd Line", "Sarla-Sason 3rd & 4th Line",
        "Salegaon-Budhapank 3rd Line", "Ahmedabad-Botad Gauge Conv.", "Bengaluru-Hassan Line"
    ],
    'State': [
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Madhya Pradesh', 'Madhya Pradesh',
        'Maharashtra', 'Maharashtra', 'Gujarat', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Odisha', 'Odisha', 'Gujarat', 'Karnataka'
    ],
    'Length_Km': [467.0, 284.0, 160.0, 300.0, 150.0, 35.0, 40.0, 307.0, 81.0, 24.0,
                 225.0, 261.0, 64.0, 284.0, 360.0, 52.0, 174.0, 297.0, 64.0, 30.0,
                 24.0, 236.0, 76.0, 132.0, 280.0, 228.0, 8.0, 120.0, 170.2, 165.4],
    'Orig_Cost': [6463.0, 2459.0, 1677.0, 2005.0, 1512.0, 263.0, 330.0, 2448.0, 673.0, 325.0,
                 3182.0, 5800.0, 1844.0, 5248.0, 18529.0, 1886.0, 5804.0, 5010.0, 3587.0, 2782.0,
                 261.0, 3426.0, 917.0, 1755.0, 2607.0, 3545.0, 252.0, 1173.0, 1205.0, 2150.0],
    'Actual_Real_World_Cost': [7109.3, 2750.0, 1928.5, 2150.0, 1620.0, 315.6, 396.0, 2815.2, 773.9, 380.0,
                              3659.3, 6670.0, 2120.6, 6035.2, 21308.3, 2168.9, 6674.6, 5761.5, 4125.0, 3199.3,
                              315.5, 3980.2, 1085.6, 2055.0, 3050.5, 4120.0, 252.0, 2092.0, 1205.0, 2490.0],
    'Expenditure': [4500.2, 1735.3, 890.1, 2100.0, 1510.0, 210.4, 185.0, 2300.5, 610.2, 195.0,
                   2850.0, 1200.0, 850.0, 2150.0, 4200.0, 600.0, 1800.0, 1150.0, 1800.0, 1250.0,
                   180.2, 2150.0, 850.0, 1450.0, 2400.0, 2850.0, 118.0, 2138.1, 950.0, 1650.0],
    'Physical_Progress_Pct': [68.5, 72.0, 55.4, 98.5, 99.0, 82.0, 58.0, 91.0, 89.5, 62.0,
                             86.0, 22.0, 48.0, 45.5, 18.0, 38.0, 32.0, 28.0, 54.0, 49.0,
                             58.0, 54.0, 80.5, 72.0, 79.5, 71.0, 92.0, 90.0, 88.0, 75.0],
    'Land_Acq_Pct': [95.0, 98.0, 85.5, 100.0, 100.0, 92.0, 88.5, 96.0, 99.0, 80.0,
                    97.5, 45.0, 65.0, 70.0, 35.0, 60.0, 55.0, 88.0, 92.0, 89.0,
                    88.0, 78.5, 95.0, 92.5, 96.0, 90.0, 100.0, 97.9, 88.0, 75.0],
    'Rainfall': [1850.4, 1420.2, 1580.6, 1650.0, 1710.5, 2305.8, 2280.4, 1540.3, 1205.1, 1340.2,
                1150.8, 1180.5, 1290.4, 1450.7, 1560.2, 1620.9, 1340.5, 1580.4, 2250.6, 2310.8,
                1340.5, 1410.2, 1650.4, 1610.8, 1580.9, 1620.2, 2149.0, 2194.3, 650.0, 850.0],
    'Labor': [0.82, 0.88, 0.79, 0.85, 0.90, 0.75, 0.77, 0.84, 0.89, 0.81,
             0.86, 0.80, 0.82, 0.81, 0.78, 0.79, 0.80, 0.83, 0.76, 0.75,
             0.82, 0.81, 0.86, 0.84, 0.85, 0.83, 0.82, 0.78, 0.82, 0.85],
    'Mineral_Data': [1.15, 1.12, 1.18, 1.05, 1.08, 1.21, 1.25, 1.11, 1.14, 1.20,
                    1.16, 1.28, 1.22, 1.19, 1.32, 1.26, 1.27, 1.24, 1.29, 1.30,
                    1.21, 1.18, 1.14, 1.16, 1.13, 1.15, 1.12, 1.41, 1.15, 1.18]
}

df_core = pd.DataFrame(data_matrix)

# ==============================================================================
# 2. SHEET 1: EARNED VALUE MANAGEMENT & PERT DERIVATIONS
# ==============================================================================
df_sheet1 = df_core.copy()

# Establishing Financial Baselines
df_sheet1['BAC'] = df_sheet1['Orig_Cost']
df_sheet1['AC'] = df_sheet1['Expenditure']
df_sheet1['EV'] = (df_sheet1['Physical_Progress_Pct'] / 100.0) * df_sheet1['BAC']

# Formulating Planned Value based on a standardized temporal assumption
df_sheet1['PV'] = df_sheet1['BAC'] * 0.75

# Deriving Variance and Performance Indices
df_sheet1['CV'] = (df_sheet1['EV'] - df_sheet1['AC']).round(2)
df_sheet1['SV'] = (df_sheet1['EV'] - df_sheet1['PV']).round(2)
df_sheet1['CPI'] = np.where(df_sheet1['AC'] == 0, 0, (df_sheet1['EV'] / df_sheet1['AC'])).round(3)
df_sheet1['SPI'] = np.where(df_sheet1['PV'] == 0, 0, (df_sheet1['EV'] / df_sheet1['PV'])).round(3)

# Projecting the Estimate at Completion using deterministic methods
df_sheet1['EAC'] = np.where(df_sheet1['CPI'] == 0, df_sheet1['BAC'], (df_sheet1['BAC'] / df_sheet1['CPI'])).round(2)

# Computing PERT Temporal Estimates (Months) mapped to physical parameters
df_sheet1['Optimistic_time'] = (df_sheet1['Length_Km'] / 10.0 + 12).round(1)
df_sheet1['Most_likely_time'] = (df_sheet1['Optimistic_time'] * 1.2 + (100 - df_sheet1['Land_Acq_Pct']) * 0.5).round(1)
df_sheet1['Pessimistic_time'] = (df_sheet1['Most_likely_time'] * 1.5 + (df_sheet1['Rainfall'] / 150.0) + (1 - df_sheet1['Labor']) * 20).round(1)
df_sheet1['PERT_Expected_Time'] = ((df_sheet1['Optimistic_time'] + 4 * df_sheet1['Most_likely_time'] + df_sheet1['Pessimistic_time']) / 6.0).round(1)

# Structuring the final export format for Sheet 1
cols_sheet1 = ['Project_ID', 'Project_Name', 'State', 'Length_Km', 'Orig_Cost', 'Land_Acq_Pct', 'Rainfall', 'Labor', 'Mineral_Data', 'BAC', 'AC', 'PV', 'EV', 'CV', 'SV', 'CPI', 'SPI', 'Optimistic_time', 'Most_likely_time', 'Pessimistic_time', 'PERT_Expected_Time', 'EAC']
export_sheet1 = df_sheet1[cols_sheet1]

# ==============================================================================
# MACHINE LEARNING PIPELINE PREPARATION
# ==============================================================================
features = ['Length_Km', 'Orig_Cost', 'Land_Acq_Pct', 'Rainfall', 'Labor', 'Mineral_Data']
X = df_core[features]
y_actual = df_core['Actual_Real_World_Cost']

# ==============================================================================
# 3. SHEET 2: XGBOOST REGRESSION WITH SHAP INTERPRETABILITY
# ==============================================================================
# Instantiating and training the XGBoost framework
xgb_model = xgb.XGBRegressor(n_estimators=250, learning_rate=0.05, max_depth=5, random_state=42)
xgb_model.fit(X, y_actual)

df_sheet2 = df_sheet1.copy()
df_sheet2['XGB_EAC'] = xgb_model.predict(X).round(2)
df_sheet2['XGB_CV'] = (df_sheet2['EV'] - df_sheet2['XGB_EAC']).round(2)
df_sheet2['XGB_SV'] = df_sheet2['SV'] # Schedule constraints remain identical
df_sheet2['XGB_CPI'] = (df_sheet2['EV'] / df_sheet2['XGB_EAC']).round(3)
df_sheet2['XGB_SPI'] = df_sheet2['SPI']

cols_sheet2 = ['Project_ID', 'Project_Name', 'State', 'BAC', 'AC', 'PV', 'EV', 'XGB_EAC', 'XGB_CV', 'XGB_SV', 'XGB_CPI', 'XGB_SPI']
export_sheet2 = df_sheet2[cols_sheet2]

# Generating SHAP values to decode the algorithmic decision-making
explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer(X)

# ==============================================================================
# 4. SHEET 3: ORDINARY LEAST SQUARES & RANDOM FOREST REGRESSION
# ==============================================================================
# Training the linear OLS model
ols_model = LinearRegression()
ols_model.fit(X, y_actual)
ols_predictions = ols_model.predict(X)

# Training the ensemble Random Forest model
rf_model = RandomForestRegressor(n_estimators=150, random_state=42)
rf_model.fit(X, y_actual)
rf_predictions = rf_model.predict(X)

df_sheet3 = df_sheet1.copy()
df_sheet3['OLS_EAC'] = np.maximum(ols_predictions, df_sheet3['AC']).round(2) # Preventing illogical predictions below already incurred costs
df_sheet3['RF_EAC'] = rf_predictions.round(2)

df_sheet3['OLS_CV'] = (df_sheet3['EV'] - df_sheet3['OLS_EAC']).round(2)
df_sheet3['RF_CV'] = (df_sheet3['EV'] - df_sheet3['RF_EAC']).round(2)
df_sheet3['OLS_CPI'] = (df_sheet3['EV'] / df_sheet3['OLS_EAC']).round(3)
df_sheet3['RF_CPI'] = (df_sheet3['EV'] / df_sheet3['RF_EAC']).round(3)

cols_sheet3 = ['Project_ID', 'Project_Name', 'State', 'BAC', 'AC', 'PV', 'EV', 'OLS_EAC', 'OLS_CV', 'OLS_CPI', 'RF_EAC', 'RF_CV', 'RF_CPI']
export_sheet3 = df_sheet3[cols_sheet3]

# ==============================================================================
# 5. SHEET 4: CROSS-METHODOLOGY ACCURACY COMPARISON
# ==============================================================================
df_comparison = pd.DataFrame({
    'Project_ID': df_core['Project_ID'],
    'Project_Name': df_core['Project_Name'],
    'Original_BAC': df_core['Orig_Cost'],
    'Actual_Real_World_Cost': df_core['Actual_Real_World_Cost'],
    'EVM_EAC': df_sheet1['EAC'],
    'OLS_EAC': df_sheet3['OLS_EAC'],
    'Random_Forest_EAC': df_sheet3['RF_EAC'],
    'XGBoost_EAC': df_sheet2['XGB_EAC']
})

# Formulating statistical summary metrics for model evaluation
summary_data = {
    'Algorithm': ['Traditional EVM', 'Ordinary Least Squares', 'Random Forest', 'XGBoost'],
    'Mean Absolute Error (MAE)': [
        round(mean_absolute_error(y_actual, df_comparison['EVM_EAC']), 2),
        round(mean_absolute_error(y_actual, df_comparison['OLS_EAC']), 2),
        round(mean_absolute_error(y_actual, df_comparison['Random_Forest_EAC']), 2),
        round(mean_absolute_error(y_actual, df_comparison['XGBoost_EAC']), 2)
    ],
    'R-Squared (R2)': [
        round(r2_score(y_actual, df_comparison['EVM_EAC']), 4),
        round(r2_score(y_actual, df_comparison['OLS_EAC']), 4),
        round(r2_score(y_actual, df_comparison['Random_Forest_EAC']), 4),
        round(r2_score(y_actual, df_comparison['XGBoost_EAC']), 4)
    ],
    'MAPE (%)': [
        round(mean_absolute_percentage_error(y_actual, df_comparison['EVM_EAC']) * 100, 2),
        round(mean_absolute_percentage_error(y_actual, df_comparison['OLS_EAC']) * 100, 2),
        round(mean_absolute_percentage_error(y_actual, df_comparison['Random_Forest_EAC']) * 100, 2),
        round(mean_absolute_percentage_error(y_actual, df_comparison['XGBoost_EAC']) * 100, 2)
    ]
}
export_summary = pd.DataFrame(summary_data)

# ==============================================================================
# 6. EXCEL WORKBOOK GENERATION
# ==============================================================================
# Leveraging the openpyxl engine to compile isolated dataframes into a unified multi-sheet workbook
output_filename = 'Infrastructure_Cost_Prediction_Analysis.xlsx'
with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
    export_sheet1.to_excel(writer, sheet_name='Sheet1_EVM_PERT', index=False)
    export_sheet2.to_excel(writer, sheet_name='Sheet2_XGBoost_SHAP', index=False)
    export_sheet3.to_excel(writer, sheet_name='Sheet3_OLS_RF', index=False)
    df_comparison.to_excel(writer, sheet_name='Sheet4_Raw_Comparison', index=False)
    export_summary.to_excel(writer, sheet_name='Sheet4_Accuracy_Metrics', index=False)

print(f"Computational pipeline complete. Multi-sheet workbook saved as: {output_filename}")

# ==============================================================================
# 7. DATA VISUALIZATION AND ANALYTICS
# ==============================================================================
plt.style.use('seaborn-v0_8-whitegrid')

# Visualization 1: Decoding the Algorithm with SHAP
plt.figure(figsize=(10, 6))
plt.title("SHAP Feature Importance Analysis (XGBoost)", fontsize=14, pad=15)
shap.summary_plot(shap_values, X, show=False)
plt.tight_layout()
plt.show()

# Visualization 2: Comparative Predictive Error
plt.figure(figsize=(10, 6))
ax = sns.barplot(x='Algorithm', y='MAPE (%)', data=export_summary, palette='magma')
plt.title('Mean Absolute Percentage Error (MAPE) Comparison', fontsize=14)
plt.ylabel('MAPE (%) - Lower is Superior')
for p in ax.patches:
    ax.annotate(f'{p.get_height()}%', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='baseline', fontsize=12, color='black', xytext=(0, 5),
                textcoords='offset points')
plt.tight_layout()
plt.show()

# Visualization 3: Predicted vs Actual Cost Distribution
plt.figure(figsize=(12, 7))
plt.scatter(df_comparison['Actual_Real_World_Cost'], df_comparison['XGBoost_EAC'], alpha=0.8, label='XGBoost Predictions', color='blue', s=80)
plt.scatter(df_comparison['Actual_Real_World_Cost'], df_comparison['OLS_EAC'], alpha=0.8, label='OLS Predictions', color='orange', marker='x', s=80)
plt.scatter(df_comparison['Actual_Real_World_Cost'], df_comparison['EVM_EAC'], alpha=0.8, label='Traditional EVM Estimates', color='green', marker='^', s=80)

# Rendering the line of perfect algorithmic prediction
max_limit = max(df_comparison['Actual_Real_World_Cost'].max(), df_comparison['XGBoost_EAC'].max())
plt.plot([0, max_limit], [0, max_limit], color='red', linestyle='--', label='Perfect Accuracy Baseline')

plt.title('Algorithmic Predictions vs. Actual Realized Costs (in ₹ Crores)', fontsize=14)
plt.xlabel('Actual Real World Cost (₹ Crores)')
plt.ylabel('Predicted Final Cost (₹ Crores)')
plt.legend()
plt.tight_layout()
plt.show()

from google.colab import files

# Trigger browser download for the generated Excel file
files.download('Infrastructure_Cost_Prediction_Analysis.xlsx')

# 1. Install required dependencies
!pip install xgboost shap pandas numpy statsmodels scikit-learn matplotlib seaborn openpyxl

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_absolute_percentage_error
import shap
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

np.random.seed(42)

# ==============================================================================
# 1. DATASET GENERATION: 30 REALISTIC RAILWAY PROJECTS
# ==============================================================================
data_30 = {
    'Project_ID': [f'PRJ_{i:03d}' for i in range(1, 31)],
    'Project_Name': [
        "Pune-Miraj-Londa Doubling", "Hotgi-Kudgi-Gadag Doubling", "Manmad-Jalgaon 3rd Line",
        "Jabalpur-Gondia Gauge Conv.", "Chhindwara-Nagpur Gauge Conv.", "Panvel-Pen Doubling",
        "Pen-Roha Doubling", "Udhna-Jalgaon Doubling", "Mudkhed-Parbhani Doubling",
        "Bhusawal-Jalgaon 3rd Line", "Daund-Gulbarga Doubling", "Ahilyanagar-Parli Vaijnath NL",
        "Baramati-Lonand New Line", "Wardha-Nanded New Line", "Indore-Manmad New Line",
        "Wadsa-Gadchiroli New Line", "Jalna-Jalgaon New Line", "Itarsi-Nagpur 4th Line",
        "Virar-Dahanu 3rd & 4th Line", "Panvel-Karjat Suburban", "Jalgaon-Bhusawal 4th Line",
        "Daund-Manmad Doubling", "Wardha-Nagpur 3rd Line", "Wardha-Ballarshah 3rd Line",
        "Itarsi-Nagpur 3rd Line", "Rajnandgaon-Nagpur 3rd Line", "3rd & 4th Line Sarla-Sason",
        "Salegaon-Budhapank 3rd Line", "Ahmedabad-Botad Gauge Conv.", "Bengaluru-Hassan Line"
    ],
    'State': [
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Madhya Pradesh', 'Madhya Pradesh',
        'Maharashtra', 'Maharashtra', 'Gujarat', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra', 'Maharashtra',
        'Maharashtra', 'Odisha', 'Odisha', 'Gujarat', 'Karnataka'
    ],
    'Length_Km': [467.0, 284.0, 160.0, 300.0, 150.0, 35.0, 40.0, 307.0, 81.0, 24.0,
                 225.0, 261.0, 64.0, 284.0, 360.0, 52.0, 174.0, 297.0, 64.0, 30.0,
                 24.0, 236.0, 76.0, 132.0, 280.0, 228.0, 8.0, 120.0, 170.2, 165.4],
    'Orig_Cost_Cr': [6463.0, 2459.0, 1677.0, 2005.0, 1512.0, 263.0, 330.0, 2448.0, 673.0, 325.0,
                     3182.0, 5800.0, 1844.0, 5248.0, 18529.0, 1886.0, 5804.0, 5010.0, 3587.0, 2782.0,
                     261.0, 3426.0, 917.0, 1755.0, 2607.0, 3545.0, 252.0, 1173.0, 1205.0, 2150.0],
    'Land_Acq_Pct': [95.0, 98.0, 85.5, 100.0, 100.0, 92.0, 88.5, 96.0, 99.0, 80.0,
                     97.5, 45.0, 65.0, 70.0, 35.0, 60.0, 55.0, 88.0, 92.0, 89.0,
                     88.0, 78.5, 95.0, 92.5, 96.0, 90.0, 100.0, 97.9, 88.0, 75.0],
    'Rainfall_mm': [1850.4, 1420.2, 1580.6, 1650.0, 1710.5, 2305.8, 2280.4, 1540.3, 1205.1, 1340.2,
                    1150.8, 1180.5, 1290.4, 1450.7, 1560.2, 1620.9, 1340.5, 1580.4, 2250.6, 2310.8,
                    1340.5, 1410.2, 1650.4, 1610.8, 1580.9, 1620.2, 2149.0, 2194.3, 650.0, 850.0],
    'Labor_Idx': [0.82, 0.88, 0.79, 0.85, 0.90, 0.75, 0.77, 0.84, 0.89, 0.81,
                  0.86, 0.80, 0.82, 0.81, 0.78, 0.79, 0.80, 0.83, 0.76, 0.75,
                  0.82, 0.81, 0.86, 0.84, 0.85, 0.83, 0.82, 0.78, 0.82, 0.85],
    'Mineral_Idx': [1.15, 1.12, 1.18, 1.05, 1.08, 1.21, 1.25, 1.11, 1.14, 1.20,
                    1.16, 1.28, 1.22, 1.19, 1.32, 1.26, 1.27, 1.24, 1.29, 1.30,
                    1.21, 1.18, 1.14, 1.16, 1.13, 1.15, 1.12, 1.41, 1.15, 1.18]
}

df_base = pd.DataFrame(data_30)

# Synthesize Time & EVM Parameters
# Planned Duration (Months) based roughly on Length, modified by a baseline metric
df_base['Planned_Duration_Months'] = (df_base['Length_Km'] / 5.0 + 24).round(1)

# Actual Real-World Duration mathematically penalized by poor land acquisition and heavy rainfall
df_base['Actual_Completion_Time_Months'] = (
    df_base['Planned_Duration_Months'] *
    (1 + (100 - df_base['Land_Acq_Pct'])/100.0) *
    (1 + df_base['Rainfall_mm']/10000.0) *
    (1.5 - df_base['Labor_Idx'])
).round(1)

# EVM Core Metrics (Assuming project is assessed at 60% of its planned timeline)
df_base['Physical_Progress_Pct'] = (df_base['Planned_Duration_Months'] / df_base['Actual_Completion_Time_Months']) * 60.0
df_base['BAC'] = df_base['Orig_Cost_Cr']
df_base['PV'] = df_base['BAC'] * 0.60
df_base['EV'] = (df_base['Physical_Progress_Pct'] / 100.0) * df_base['BAC']
df_base['AC'] = df_base['EV'] * (df_base['Mineral_Idx']) # Adjust actual cost based on material inflation

# PERT Task Estimates (Months)
df_base['Optimistic_Time'] = (df_base['Planned_Duration_Months'] * 0.9).round(1)
df_base['Most_Likely_Time'] = df_base['Planned_Duration_Months']
df_base['Pessimistic_Time'] = (df_base['Planned_Duration_Months'] * 1.5 + (100 - df_base['Land_Acq_Pct'])*0.5).round(1)

# ==============================================================================
# 2. SHEET 1: EVM, CPM & PERT TIME FORECASTING
# ==============================================================================
sheet1_df = df_base.copy()

sheet1_df['CV'] = (sheet1_df['EV'] - sheet1_df['AC']).round(2)
sheet1_df['SV'] = (sheet1_df['EV'] - sheet1_df['PV']).round(2)
sheet1_df['CPI'] = (sheet1_df['EV'] / sheet1_df['AC']).round(3)
sheet1_df['SPI'] = (sheet1_df['EV'] / sheet1_df['PV']).round(3)

# Time Estimate at Completion (EVM)
sheet1_df['EAC_Time_EVM'] = (sheet1_df['Planned_Duration_Months'] / sheet1_df['SPI']).round(1)
# Expected Duration (PERT)
sheet1_df['EAC_Time_PERT'] = ((sheet1_df['Optimistic_Time'] + 4 * sheet1_df['Most_Likely_Time'] + sheet1_df['Pessimistic_Time']) / 6.0).round(1)

cols_sheet1 = ['Project_ID', 'Project_Name', 'State', 'Length_Km', 'Orig_Cost_Cr', 'Land_Acq_Pct', 'Rainfall_mm', 'Labor_Idx', 'Mineral_Idx',
               'Planned_Duration_Months', 'BAC', 'PV', 'EV', 'AC', 'SV', 'CV', 'CPI', 'SPI',
               'Optimistic_Time', 'Most_Likely_Time', 'Pessimistic_Time', 'EAC_Time_PERT', 'EAC_Time_EVM']
export_sheet1 = sheet1_df[cols_sheet1]

# ==============================================================================
# 3. SHEET 2: XGBOOST TIME REGRESSION WITH SHAP
# ==============================================================================
features = ['Length_Km', 'Orig_Cost_Cr', 'Land_Acq_Pct', 'Rainfall_mm', 'Labor_Idx', 'Mineral_Idx']
X = df_base[features]
y_time = df_base['Actual_Completion_Time_Months']

xgb_model = xgb.XGBRegressor(n_estimators=200, learning_rate=0.1, max_depth=4, random_state=42)
xgb_model.fit(X, y_time)

sheet2_df = sheet1_df.copy()
sheet2_df['XGBoost_EAC_Time'] = xgb_model.predict(X).round(1)
sheet2_df['XGBoost_SPI_Forecast'] = (sheet2_df['Planned_Duration_Months'] / sheet2_df['XGBoost_EAC_Time']).round(3)

cols_sheet2 = ['Project_ID', 'Project_Name', 'State', 'Planned_Duration_Months', 'Actual_Completion_Time_Months', 'XGBoost_EAC_Time', 'XGBoost_SPI_Forecast']
export_sheet2 = sheet2_df[cols_sheet2]

# SHAP Values for visualization
explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer(X)

# ==============================================================================
# 4. SHEET 3: OLS & RANDOM FOREST TIME REGRESSION
# ==============================================================================
ols_model = LinearRegression().fit(X, y_time)
rf_model = RandomForestRegressor(n_estimators=100, random_state=42).fit(X, y_time)

sheet3_df = sheet1_df.copy()
sheet3_df['OLS_EAC_Time'] = ols_model.predict(X).round(1)
sheet3_df['RF_EAC_Time'] = rf_model.predict(X).round(1)

cols_sheet3 = ['Project_ID', 'Project_Name', 'State', 'Planned_Duration_Months', 'Actual_Completion_Time_Months', 'OLS_EAC_Time', 'RF_EAC_Time']
export_sheet3 = sheet3_df[cols_sheet3]

# ==============================================================================
# 5. SHEET 4: COMPARATIVE ANALYSIS
# ==============================================================================
comp_df = pd.DataFrame({
    'Project_ID': df_base['Project_ID'],
    'Project_Name': df_base['Project_Name'],
    'Planned_Time_Months': df_base['Planned_Duration_Months'],
    'Actual_Real_World_Time': df_base['Actual_Completion_Time_Months'],
    'EVM_Predicted_Time': sheet1_df['EAC_Time_EVM'],
    'PERT_Predicted_Time': sheet1_df['EAC_Time_PERT'],
    'OLS_Predicted_Time': sheet3_df['OLS_EAC_Time'],
    'RandomForest_Predicted_Time': sheet3_df['RF_EAC_Time'],
    'XGBoost_Predicted_Time': sheet2_df['XGBoost_EAC_Time']
})

def calculate_accuracy(true, pred):
    mape = mean_absolute_percentage_error(true, pred)
    return round((1 - mape) * 100, 2)

summary_data = {
    'Algorithm': ['Traditional EVM', 'PERT Expected', 'Ordinary Least Squares', 'Random Forest', 'XGBoost'],
    'Mean Absolute Error (Months)': [
        round(mean_absolute_error(y_time, comp_df['EVM_Predicted_Time']), 2),
        round(mean_absolute_error(y_time, comp_df['PERT_Predicted_Time']), 2),
        round(mean_absolute_error(y_time, comp_df['OLS_Predicted_Time']), 2),
        round(mean_absolute_error(y_time, comp_df['RandomForest_Predicted_Time']), 2),
        round(mean_absolute_error(y_time, comp_df['XGBoost_Predicted_Time']), 2)
    ],
    'Accuracy (%)': [
        calculate_accuracy(y_time, comp_df['EVM_Predicted_Time']),
        calculate_accuracy(y_time, comp_df['PERT_Predicted_Time']),
        calculate_accuracy(y_time, comp_df['OLS_Predicted_Time']),
        calculate_accuracy(y_time, comp_df['RandomForest_Predicted_Time']),
        calculate_accuracy(y_time, comp_df['XGBoost_Predicted_Time'])
    ]
}
export_summary = pd.DataFrame(summary_data)

# ==============================================================================
# 6. EXCEL WORKBOOK GENERATION
# ==============================================================================
output_filename = 'Infrastructure_Time_Prediction_Analysis.xlsx'
with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
    export_sheet1.to_excel(writer, sheet_name='Sheet1_EVM_PERT_Time', index=False)
    export_sheet2.to_excel(writer, sheet_name='Sheet2_XGBoost_SHAP', index=False)
    export_sheet3.to_excel(writer, sheet_name='Sheet3_OLS_RF_Time', index=False)
    comp_df.to_excel(writer, sheet_name='Sheet4_Data_Comparison', index=False)
    export_summary.to_excel(writer, sheet_name='Sheet4_Accuracy_Metrics', index=False)

print(f"Data Generation & Analysis Complete! Multi-sheet workbook saved as: {output_filename}\n")

# ==============================================================================
# 7. DATA VISUALIZATION
# ==============================================================================
plt.style.use('seaborn-v0_8-whitegrid')

# Visualization 1: XGBoost Accuracy & Feature Impact via SHAP
plt.figure(figsize=(9, 5))
plt.title("SHAP Analysis: Key Drivers of Project Time Delays", fontsize=14, pad=15)
shap.summary_plot(shap_values, X, show=False)
plt.tight_layout()
plt.show()

# Visualization 2: Accuracy Comparison Across Models
plt.figure(figsize=(10, 6))
ax = sns.barplot(x='Algorithm', y='Accuracy (%)', data=export_summary, palette='viridis')
plt.title('Time Prediction Accuracy Comparison (Higher is Better)', fontsize=14)
plt.ylabel('Prediction Accuracy (%)')
plt.ylim(0, 100)
for p in ax.patches:
    ax.annotate(f'{p.get_height()}%', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='baseline', fontsize=12, color='black', xytext=(0, 5),
                textcoords='offset points')
plt.tight_layout()
plt.show()

# Visualization 3: Predicted Time vs Actual Time Scatter Plot
plt.figure(figsize=(11, 7))
plt.scatter(comp_df['Actual_Real_World_Time'], comp_df['XGBoost_Predicted_Time'], label='XGBoost', color='blue', alpha=0.7, s=70)
plt.scatter(comp_df['Actual_Real_World_Time'], comp_df['RandomForest_Predicted_Time'], label='Random Forest', color='purple', alpha=0.7, s=70, marker='s')
plt.scatter(comp_df['Actual_Real_World_Time'], comp_df['OLS_Predicted_Time'], label='OLS Regression', color='orange', alpha=0.7, s=70, marker='x')
plt.scatter(comp_df['Actual_Real_World_Time'], comp_df['EVM_Predicted_Time'], label='Traditional EVM', color='red', alpha=0.7, s=70, marker='^')

# Perfect Prediction Line
max_time = max(comp_df['Actual_Real_World_Time'].max(), comp_df['EVM_Predicted_Time'].max())
plt.plot([0, max_time], [0, max_time], color='black', linestyle='--', label='Perfect Accuracy')

plt.title('Predicted vs. Actual Completion Time (Months)', fontsize=14)
plt.xlabel('Actual Real-World Duration (Months)')
plt.ylabel('Algorithm Predicted Duration (Months)')
plt.legend()
plt.tight_layout()
plt.show()

from google.colab import files

# Trigger the download for the generated Excel sheet
files.download('Infrastructure_Time_Prediction_Analysis.xlsx')

# ==============================================================================
# ADVANCED DATA VISUALIZATION SUITE FOR RAILWAY INFRASTRUCTURE RESEARCH
# Modules: EVM Analytics, OLS vs. XGBoost Benchmarking, SHAP XAI, PERT/CPM, & Risks
# Output: High-DPI Vector PDFs & PNGs packaged into an automatic ZIP download
# ==============================================================================

# 1. Install necessary dependencies in Colab
!pip install xgboost shap pandas numpy statsmodels matplotlib seaborn scipy openpyxl -q

import os
import shutil
import zipfile
import numpy as np
import pandas as pd
import statsmodels.api as sm
import xgboost as xgb
import shap
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from google.colab import files
import warnings
warnings.filterwarnings('ignore')

# ------------------------------------------------------------------------------
# 2. Journal Publication Styling Parameters (ASCE / Elsevier Specifications)
# ------------------------------------------------------------------------------
OUTPUT_DIR = "Railway_Research_Figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['DejaVu Sans', 'Arial', 'Helvetica'],
    'font.size': 9,
    'axes.labelsize': 10,
    'axes.titlesize': 11,
    'xtick.labelsize': 8.5,
    'ytick.labelsize': 8.5,
    'legend.fontsize': 8.5,
    'figure.titlesize': 12,
    'figure.autolayout': False,
    'axes.linewidth': 0.8,
    'grid.linewidth': 0.5,
    'grid.alpha': 0.4,
    'savefig.dpi': 600,
    'savefig.bbox': 'tight'
})

# ------------------------------------------------------------------------------
# 3. Data Synthesis: 30 Real-World Testing Projects & Multi-Model Metrics
# ------------------------------------------------------------------------------
np.random.seed(42)

project_names = [
    "Virar-Dahanu Road 3rd & 4th Line", "Ahmedabad-Botad Gauge Conversion",
    "Khurda Road-Bolangir New Line", "Jhansi-Manikpur Doubling",
    "Mau-Ghazipur-Tarighat New Line", "Bengaluru-Hassan Line Doubling",
    "Howrah-Bardhaman Chord Line", "New Bongaigaon-Rangia-Kamakhya Doubling",
    "Ajmer-Chittaurgarh Gauge Conversion", "Kazipet-Balharshah 3rd Line",
    "Indore-Manmad New Line", "Wardha-Nanded New Line",
    "Pune-Miraj-Londa Doubling", "Daund-Manmad Doubling",
    "Itarsi-Nagpur 4th Line", "Panvel-Karjat Suburban Corridor",
    "Kalyan-Kasara 3rd Line", "Gonda-Gorakhpur Doubling",
    "Sabarmati-Agra High-Speed Link", "Raipur-Titlagarh Doubling",
    "Katni-Bina 3rd Line", "Bhusawal-Khandwa 3rd & 4th Line",
    "Solapur-Tuljapur-Osmanabad New Line", "Gooty-Renigunta Doubling",
    "Secunderabad-Mahabubnagar Doubling", "Harbour Line Goregaon-Borivali Extension",
    "Ratlam-Neemuch Doubling", "Ranchi-Lohardaga Gauge Conversion",
    "Hospet-Hubli-Tinaighat Doubling", "Sevok-Rangpo New Line"
]

states = ['Maharashtra', 'Gujarat', 'Odisha', 'Karnataka', 'Uttar Pradesh',
          'Bihar', 'West Bengal', 'Assam', 'Rajasthan', 'Telangana']
n = len(project_names)

df = pd.DataFrame({
    'Project_ID': [f'TEST_{i+1:03d}' for i in range(n)],
    'Project_Name': project_names,
    'State': np.random.choice(states, n),
    'Length_Km': np.random.uniform(25, 360, n).round(1),
    'Original_Cost_Cr': np.random.uniform(200, 5000, n).round(1),
    'Land_Acq_Pct': np.random.uniform(30, 98, n).round(1),
    'Agg_Rainfall_mm': np.random.uniform(500, 2400, n).round(1),
    'Labor_Avail_Idx': np.random.uniform(0.68, 0.94, n).round(2),
    'Mineral_Mat_Idx': np.random.uniform(1.08, 1.42, n).round(2),
    'Physical_Progress_Pct': np.random.uniform(25, 95, n).round(1),
    'Actual_Delay_Years': np.random.uniform(0.8, 5.2, n).round(2)
})

# PERT Task Estimations (T1 to T5 in Weeks)
df['T1_O'], df['T1_M'], df['T1_P'] = 8, 12, 22
df['T2_O'], df['T2_M'] = 20, 35
df['T2_P'] = df['T2_M'] + ((100 - df['Land_Acq_Pct']) * 1.4).astype(int)
df['T3_O'], df['T3_M'] = 15, 25
df['T3_P'] = df['T3_M'] + (df['Agg_Rainfall_mm'] / 45).astype(int)
df['T4_O'] = (df['Length_Km'] / 12).astype(int) + 6
df['T4_M'] = df['T4_O'] + 14
df['T4_P'] = df['T4_M'] + 22
df['T5_O'], df['T5_M'], df['T5_P'] = 10, 16, 26
df['Target_Deadline_Weeks'] = df['T1_M'] + df['T2_M'] + df['T3_M'] + df['T4_M'] + df['T5_M'] + 10

# Earned Value Management (EVM) Parameter Formulations
df['BAC'] = df['Original_Cost_Cr']
df['PV'] = df['BAC'] * 0.70  # Reference baseline progress at 70% planned cut-off
df['EV'] = df['BAC'] * (df['Physical_Progress_Pct'] / 100.0)
cost_escalation_factor = 1.0 + (df['Actual_Delay_Years'] * 0.08) + ((df['Mineral_Mat_Idx'] - 1.0) * 0.5)
df['AC'] = (df['EV'] * cost_escalation_factor).round(2)
df['CV'] = (df['EV'] - df['AC']).round(2)
df['SV'] = (df['EV'] - df['PV']).round(2)
df['CPI'] = (df['EV'] / df['AC']).round(3)
df['SPI'] = (df['EV'] / df['PV']).round(3)
df['EAC'] = (df['BAC'] / df['CPI']).round(2)

# PERT Schedule Computations
def run_pert(row):
    tasks = ['T1', 'T2', 'T3', 'T4', 'T5']
    te, var = {}, {}
    for t in tasks:
        te[t] = (row[f'{t}_O'] + 4*row[f'{t}_M'] + row[f'{t}_P']) / 6.0
        var[t] = ((row[f'{t}_P'] - row[f'{t}_O']) / 6.0) ** 2
    # Critical Path: T1 -> max(T2, T3) -> T4 -> T5
    crit_branch = 'T2' if te['T2'] > te['T3'] else 'T3'
    crit_tasks = ['T1', crit_branch, 'T4', 'T5']
    te_proj = sum(te[t] for t in crit_tasks)
    std_proj = np.sqrt(sum(var[t] for t in crit_tasks))
    z_score = (row['Target_Deadline_Weeks'] - te_proj) / std_proj
    prob = norm.cdf(z_score) * 100.0
    return pd.Series([te_proj, std_proj, prob, te_proj / 52.14],
                     index=['PERT_TE_Weeks', 'PERT_Std_Weeks', 'PERT_Prob_Pct', 'PERT_Predicted_Delay'])

pert_res = df.apply(run_pert, axis=1)
df = pd.concat([df, pert_res], axis=1)

# Predictive Modeling: OLS and XGBoost
features = ['Length_Km', 'Original_Cost_Cr', 'Land_Acq_Pct', 'Agg_Rainfall_mm', 'Labor_Avail_Idx', 'Mineral_Mat_Idx']
X = df[features]
y = df['Actual_Delay_Years']

# 1. OLS Baseline
X_ols = sm.add_constant(X)
ols_model = sm.OLS(y, X_ols).fit()
df['OLS_Predicted_Delay'] = ols_model.predict(X_ols)

# 2. XGBoost ML Model
xgb_model = xgb.XGBRegressor(n_estimators=120, max_depth=3, learning_rate=0.08, random_state=42)
xgb_model.fit(X, y)
df['XGB_Predicted_Delay'] = xgb_model.predict(X)

# ------------------------------------------------------------------------------
# 4. Visualization Production
# ------------------------------------------------------------------------------

def export_figure(fig, base_name):
    """Saves both vector PDF and 600 DPI PNG figures for journals and presentations."""
    pdf_path = os.path.join(OUTPUT_DIR, f"{base_name}.pdf")
    png_path = os.path.join(OUTPUT_DIR, f"{base_name}.png")
    fig.savefig(pdf_path, format='pdf', dpi=600, bbox_inches='tight')
    fig.savefig(png_path, format='png', dpi=600, bbox_inches='tight')
    plt.close(fig)
    print(f"Exported: {base_name}.pdf and {base_name}.png")

# ------------------------------------------------------------------------------
# FIGURE 1: EVM Cumulative S-Curve & Project Health Performance Quadrant
# ------------------------------------------------------------------------------
fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.5))

# S-Curve Panel
sorted_df = df.sort_values(by='Physical_Progress_Pct').reset_index(drop=True)
pct = sorted_df['Physical_Progress_Pct']
ax1.plot(pct, sorted_df['PV'].cumsum(), label='Planned Value (PV)', color='#1f77b4', lw=2.2, linestyle='--')
ax1.plot(pct, sorted_df['EV'].cumsum(), label='Earned Value (EV)', color='#2ca02c', lw=2.2)
ax1.plot(pct, sorted_df['AC'].cumsum(), label='Actual Cost (AC)', color='#d62728', lw=2.2)
ax1.fill_between(pct, sorted_df['EV'].cumsum(), sorted_df['AC'].cumsum(), color='#d62728', alpha=0.15, label='Cost Overrun Variance')
ax1.set_xlabel('Physical Progress (%)')
ax1.set_ylabel('Cumulative Capital Expenditure (₹ Crore)')
ax1.set_title('(a) Cumulative EVM Portfolio Cashflow & Progress S-Curve', pad=10)
ax1.grid(True, linestyle=':')
ax1.legend(loc='upper left', frameon=True)

# Performance Indices Quadrant
scatter = ax2.scatter(df['SPI'], df['CPI'], c=df['Original_Cost_Cr'], cmap='viridis', s=df['Actual_Delay_Years']*25, alpha=0.85, edgecolors='k', lw=0.6)
ax2.axvline(1.0, color='gray', linestyle='--', lw=1.2)
ax2.axhline(1.0, color='gray', linestyle='--', lw=1.2)
ax2.axhspan(1.0, 1.3, xmin=0.5, xmax=1.0, color='#2ca02c', alpha=0.08)
ax2.axhspan(0.5, 1.0, xmin=0.0, xmax=0.5, color='#d62728', alpha=0.08)
ax2.text(1.08, 1.05, 'Favorable\n(Under Budget, Ahead)', fontsize=8, color='green', weight='bold')
ax2.text(0.60, 0.65, 'Critical Risk\n(Over Budget, Delayed)', fontsize=8, color='red', weight='bold')
ax2.set_xlabel('Schedule Performance Index (SPI)')
ax2.set_ylabel('Cost Performance Index (CPI)')
ax2.set_title('(b) EVM Performance Index (CPI vs. SPI) Matrix', pad=10)
cbar = plt.colorbar(scatter, ax=ax2)
cbar.set_label('Original Budget (₹ Cr)')
ax2.grid(True, linestyle=':')

plt.tight_layout()
export_figure(fig1, "Figure_1_EVM_Performance_Matrix")

# ------------------------------------------------------------------------------
# FIGURE 2: Predictive Parity & Residual Scatter Distributions (OLS vs. XGBoost)
# ------------------------------------------------------------------------------
fig2, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(12, 10))

# Parity Plots
min_val, max_val = 0.5, 6.0
for ax, col, title, color in zip([ax1, ax2], ['OLS_Predicted_Delay', 'XGB_Predicted_Delay'],
                                  ['OLS Linear Baseline Parity', 'XGBoost Non-Linear Parity'], ['#1f77b4', '#d62728']):
    ax.plot([min_val, max_val], [min_val, max_val], 'k--', lw=1.5, label='1:1 Parity Line')
    ax.fill_between([min_val, max_val], [min_val*0.85, max_val*0.85], [min_val*1.15, max_val*1.15], color='gray', alpha=0.15, label='±15% Error Band')
    ax.scatter(df['Actual_Delay_Years'], df[col], color=color, alpha=0.85, edgecolors='k', lw=0.6, s=45)
    r2 = r2_score(df['Actual_Delay_Years'], df[col])
    rmse = np.sqrt(mean_squared_error(df['Actual_Delay_Years'], df[col]))
    ax.text(0.05, 0.88, f"$R^2 = {r2:.3f}$\n$RMSE = {rmse:.2f}$ Yrs", transform=ax.transAxes,
            bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", lw=0.6))
    ax.set_xlabel('Actual Recorded Delay (Years)')
    ax.set_ylabel('Predicted Delay (Years)')
    ax.set_title(title)
    ax.grid(True, linestyle=':')
    ax.legend(loc='lower right')

# Residual Plots
for ax, col, title, color in zip([ax3, ax4], ['OLS_Predicted_Delay', 'XGB_Predicted_Delay'],
                                  ['OLS Residual Distribution', 'XGBoost Residual Distribution'], ['#1f77b4', '#d62728']):
    res = df['Actual_Delay_Years'] - df[col]
    ax.scatter(df[col], res, color=color, alpha=0.85, edgecolors='k', lw=0.6, s=45)
    ax.axhline(0, color='black', linestyle='--', lw=1.2)
    ax.set_xlabel('Fitted / Predicted Values (Years)')
    ax.set_ylabel('Residuals (Actual - Predicted)')
    ax.set_title(title)
    ax.grid(True, linestyle=':')

plt.tight_layout()
export_figure(fig2, "Figure_2_Parity_and_Residual_Diagnostics")

# ------------------------------------------------------------------------------
# FIGURE 3: Comparative Goodness-of-Fit Model Benchmark
# ------------------------------------------------------------------------------
fig3, ax = plt.subplots(figsize=(9, 5))

def get_metrics(actual, pred):
    r2 = r2_score(actual, pred)
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    mape = np.mean(np.abs((actual - pred) / actual)) * 100
    return [r2, rmse, mae, mape]

metrics_data = {
    'Metric': ['$R^2$ Score', 'RMSE (Years)', 'MAE (Years)', 'MAPE (%) / 10'],
    'PERT / CPM': [0.41, 1.48, 1.22, 4.82],
    'OLS Baseline': get_metrics(df['Actual_Delay_Years'], df['OLS_Predicted_Delay'])[:3] + [get_metrics(df['Actual_Delay_Years'], df['OLS_Predicted_Delay'])[3]/10.0],
    'XGBoost ML': get_metrics(df['Actual_Delay_Years'], df['XGB_Predicted_Delay'])[:3] + [get_metrics(df['Actual_Delay_Years'], df['XGB_Predicted_Delay'])[3]/10.0]
}

m_df = pd.DataFrame(metrics_data).melt(id_vars='Metric', var_name='Analytical Model', value_name='Value')
sns.barplot(data=m_df, x='Metric', y='Value', hue='Analytical Model', palette=['#7f7f7f', '#1f77b4', '#2ca02c'], ax=ax, edgecolor='k', lw=0.6)
ax.set_ylabel('Performance Value (Normalized)')
ax.set_title('Comparative Prediction Accuracy Across Analytical Methodologies', pad=12)
ax.grid(True, axis='y', linestyle=':')
ax.legend(frameon=True, facecolor='white')

for p in ax.patches:
    h = p.get_height()
    if not np.isnan(h) and h > 0:
        ax.annotate(f"{h:.2f}", (p.get_x() + p.get_width() / 2., h), ha='center', va='bottom', fontsize=7.5, xytext=(0, 2), textcoords='offset points')

plt.tight_layout()
export_figure(fig3, "Figure_3_Comparative_Model_Benchmark")

# ------------------------------------------------------------------------------
# FIGURE 4: Explainable AI (SHAP Global Summary & Feature Importance)
# ------------------------------------------------------------------------------
explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer(X)

fig4, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))

# SHAP Beeswarm Plot
plt.sca(ax1)
shap.plots.beeswarm(shap_values, max_display=6, show=False)
ax1.set_title('(a) SHAP Global Feature Contribution Dynamics', pad=10)

# SHAP Absolute Mean Importance Bar Plot
mean_shap = np.abs(shap_values.values).mean(axis=0)
feat_importance = pd.DataFrame({'Feature': features, 'Importance': mean_shap}).sort_values(by='Importance', ascending=True)

ax2.barh(feat_importance['Feature'], feat_importance['Importance'], color='#3182bd', edgecolor='k', lw=0.6, height=0.6)
ax2.set_xlabel('Mean Absolute SHAP Value (Impact on Delay in Years)')
ax2.set_title('(b) Hierarchical Feature Ranking (XGBoost)', pad=10)
ax2.grid(True, axis='x', linestyle=':')

for idx, val in enumerate(feat_importance['Importance']):
    ax2.text(val + 0.01, idx, f"{val:.3f}", va='center', fontsize=8)

plt.tight_layout()
export_figure(fig4, "Figure_4_SHAP_Interpretability_Summary")

# ------------------------------------------------------------------------------
# FIGURE 5: PERT/CPM Stochastic Probability & Critical Path Delay Breakdown
# ------------------------------------------------------------------------------
fig5, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.2))

# Normal Distribution Schedule PDF
target_p = df.iloc[0]
mu = target_p['PERT_TE_Weeks']
sigma = target_p['PERT_Std_Weeks']
target_line = target_p['Target_Deadline_Weeks']

x_axis = np.linspace(mu - 3.5*sigma, mu + 3.5*sigma, 500)
y_pdf = norm.pdf(x_axis, mu, sigma)
ax1.plot(x_axis, y_pdf, color='#1f77b4', lw=2.2, label=f'PERT Normal Density ($\mu={mu:.1f}$, $\sigma={sigma:.1f}$ Wks)')
ax1.fill_between(x_axis, y_pdf, where=(x_axis <= target_line), color='#2ca02c', alpha=0.3, label=f'Prob. on Time ({target_p["PERT_Prob_Pct"]:.1f}%)')
ax1.fill_between(x_axis, y_pdf, where=(x_axis > target_line), color='#d62728', alpha=0.25, label='Prob. of Schedule Overrun')
ax1.axvline(target_line, color='black', linestyle='--', lw=1.5, label=f'Target Deadline ({target_line:.0f} Wks)')
ax1.set_xlabel('Total Project Duration (Weeks)')
ax1.set_ylabel('Probability Density Function')
ax1.set_title(f'(a) Probabilistic Schedule Risk (Project: {target_p["Project_ID"]})', pad=10)
ax1.grid(True, linestyle=':')
ax1.legend(loc='upper right', frameon=True)

# Task Criticality & Variance Bar Breakdown
tasks = ['T1: Admin', 'T2: Land Acq', 'T3: Earthworks', 'T4: Track Link', 'T5: Signalling']
te_vals = [
    (target_p['T1_O'] + 4*target_p['T1_M'] + target_p['T1_P'])/6.0,
    (target_p['T2_O'] + 4*target_p['T2_M'] + target_p['T2_P'])/6.0,
    (target_p['T3_O'] + 4*target_p['T3_M'] + target_p['T3_P'])/6.0,
    (target_p['T4_O'] + 4*target_p['T4_M'] + target_p['T4_P'])/6.0,
    (target_p['T5_O'] + 4*target_p['T5_M'] + target_p['T5_P'])/6.0
]
bar_colors = ['#aec7e8', '#d62728', '#aec7e8', '#d62728', '#d62728'] # Red denotes Critical Path
ax2.bar(tasks, te_vals, color=bar_colors, edgecolor='k', lw=0.6, width=0.55)
ax2.set_ylabel('Expected Task Duration $T_E$ (Weeks)')
ax2.set_title('(b) Activity-on-Node Expected Durations (Red = Critical Path)', pad=10)
ax2.grid(True, axis='y', linestyle=':')

for i, v in enumerate(te_vals):
    ax2.text(i, v + 0.8, f"{v:.1f}w", ha='center', fontsize=8.5, weight='bold')

plt.tight_layout()
export_figure(fig5, "Figure_5_PERT_Probabilistic_Schedule_Risk")

# ------------------------------------------------------------------------------
# FIGURE 6: Regional Risk Drivers & Parameter Correlation Heatmap
# ------------------------------------------------------------------------------
fig6, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))

# Correlation Heatmap
corr_cols = ['Length_Km', 'Original_Cost_Cr', 'Land_Acq_Pct', 'Agg_Rainfall_mm',
             'Labor_Avail_Idx', 'Mineral_Mat_Idx', 'Actual_Delay_Years', 'CPI', 'SPI']
corr_matrix = df[corr_cols].corr()
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
cmap = sns.diverging_palette(230, 20, as_cmap=True)
sns.heatmap(corr_matrix, mask=mask, cmap=cmap, vmax=1.0, vmin=-1.0, center=0,
            annot=True, fmt=".2f", square=True, linewidths=0.6, ax=ax1, cbar_kws={"shrink": 0.8})
ax1.set_title('(a) Multi-Factor Pearson Correlation Matrix', pad=10)

# State-Wise Delay Distribution
state_order = df.groupby('State')['Actual_Delay_Years'].median().sort_values(ascending=False).index
sns.boxplot(data=df, x='State', y='Actual_Delay_Years', order=state_order, palette='Set2', ax=ax2, linewidth=0.8, fliersize=3)
ax2.set_xticklabels(ax2.get_xticklabels(), rotation=45, ha='right')
ax2.set_xlabel('State Railway Zone')
ax2.set_ylabel('Actual Project Delay (Years)')
ax2.set_title('(b) Empirical Delay Severity Across Indian States', pad=10)
ax2.grid(True, axis='y', linestyle=':')

plt.tight_layout()
export_figure(fig6, "Figure_6_Risk_Correlation_and_State_Variance")

# ------------------------------------------------------------------------------
# 5. Archive Files & Trigger Automatic Download
# ------------------------------------------------------------------------------
zip_filename = "Railway_Research_Visuals_VJTI.zip"
with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, _, filenames in os.walk(OUTPUT_DIR):
        for f in filenames:
            zipf.write(os.path.join(root, f), arcname=f)

print(f"\nSuccessfully generated all figures in '{OUTPUT_DIR}'.")
print(f"Triggering automated download for '{zip_filename}'...")
files.download(zip_filename)